//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWpfMVVM.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicWpfMVVM.Resources.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the application.
        /// </summary>
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average number of people on the floor:.
        /// </summary>
        public static string avg {
            get {
                return ResourceManager.GetString("avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building capacity.
        /// </summary>
        public static string BuildingCapacity {
            get {
                return ResourceManager.GetString("BuildingCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building:.
        /// </summary>
        public static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JT6.
        /// </summary>
        public static string FirstBuilding {
            get {
                return ResourceManager.GetString("FirstBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor 1.
        /// </summary>
        public static string Floor1 {
            get {
                return ResourceManager.GetString("Floor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor 2.
        /// </summary>
        public static string Floor2 {
            get {
                return ResourceManager.GetString("Floor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor 3.
        /// </summary>
        public static string Floor3 {
            get {
                return ResourceManager.GetString("Floor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor 4.
        /// </summary>
        public static string Floor4 {
            get {
                return ResourceManager.GetString("Floor4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor 5.
        /// </summary>
        public static string Floor5 {
            get {
                return ResourceManager.GetString("Floor5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor 6.
        /// </summary>
        public static string Floor6 {
            get {
                return ResourceManager.GetString("Floor6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor capacity.
        /// </summary>
        public static string FloorCapacity {
            get {
                return ResourceManager.GetString("FloorCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string Floors {
            get {
                return ResourceManager.GetString("Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of people in the room:.
        /// </summary>
        public static string max {
            get {
                return ResourceManager.GetString("max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of people in the room:.
        /// </summary>
        public static string min {
            get {
                return ResourceManager.GetString("min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation.
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people in the building.
        /// </summary>
        public static string NumOfPeopleInBuilding {
            get {
                return ResourceManager.GetString("NumOfPeopleInBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people on the floor.
        /// </summary>
        public static string NumOfPeopleOnFloor {
            get {
                return ResourceManager.GetString("NumOfPeopleOnFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rooms in the building.
        /// </summary>
        public static string NumOfRoomsInBuilding {
            get {
                return ResourceManager.GetString("NumOfRoomsInBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rooms on the floor.
        /// </summary>
        public static string NumOfRoomsOnFloor {
            get {
                return ResourceManager.GetString("NumOfRoomsOnFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string Room {
            get {
                return ResourceManager.GetString("Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JT8.
        /// </summary>
        public static string SecondBuilding {
            get {
                return ResourceManager.GetString("SecondBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many thanks to our great tutor:.
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This seating order program is the result of FPT Summer School 2016 (v3.0). If you think the application is super cool, feel free to contact us, otherwise don’t hesitate to try it again! :).
        /// </summary>
        public static string ThisApp {
            get {
                return ResourceManager.GetString("ThisApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
